# generated by datamodel-codegen:
#   filename:  fiken-api-swagger.yaml
#   timestamp: 2025-12-10T18:24:18+00:00

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field


class Account(BaseModel):
    code: Annotated[str | None, Field(examples=["1500:10029"])] = None
    name: Annotated[str | None, Field(examples=["John Lewis"])] = None


class Address(BaseModel):
    street_address: Annotated[
        str | None, Field(alias="streetAddress", examples=["Karl Johan 34"])
    ] = None
    street_address_line2: Annotated[
        str | None, Field(alias="streetAddressLine2", examples=["H0405"])
    ] = None
    city: Annotated[str | None, Field(examples=["Oslo"])] = None
    post_code: Annotated[str | None, Field(alias="postCode", examples=["0550"])] = None
    country: Annotated[str, Field(examples=["Norway"])]


class Type(StrEnum):
    invoice = "invoice"
    reminder = "reminder"
    unspecified = "unspecified"
    ocr = "ocr"
    bank_statement = "bank_statement"


class Attachment(BaseModel):
    identifier: Annotated[
        str | None,
        Field(
            description="User-defined identifier for attachment. Could be the Invoice Id or receipt number for example.",
            examples=["24760"],
        ),
    ] = None
    download_url: Annotated[
        str | None,
        Field(
            alias="downloadUrl",
            description="For use with API credentials (bearer token or oauth 2)",
        ),
    ] = None
    download_url_with_fiken_normal_user_credentials: Annotated[
        str | None,
        Field(
            alias="downloadUrlWithFikenNormalUserCredentials",
            description="Requires the user to login with username and password in Fiken.",
        ),
    ] = None
    comment: Annotated[
        str | None,
        Field(description="Field for additional information for this attachment."),
    ] = None
    type: Annotated[Type | None, Field(examples=["invoice"])] = None


class Type1(StrEnum):
    normal = "normal"
    tax_deduction = "tax_deduction"
    foreign = "foreign"
    credit_card = "credit_card"


class BankAccountRequest(BaseModel):
    name: Annotated[str, Field(examples=["Utgiftskonto DNB"])]
    bank_account_number: Annotated[
        str, Field(alias="bankAccountNumber", examples=["11112233334"])
    ]
    bic: Annotated[str | None, Field(examples=["DNBANOKKXXX"])] = None
    iban: Annotated[str | None, Field(examples=["NO49 1111 2233 334"])] = None
    foreign_service: Annotated[
        str | None, Field(alias="foreignService", examples=["Barclays UK"])
    ] = None
    type: Annotated[Type1, Field(examples=["normal"])]
    inactive: Annotated[bool | None, Field(examples=[False])] = False


class BankAccountResult(BaseModel):
    bank_account_id: Annotated[
        int | None, Field(alias="bankAccountId", examples=[2747365])
    ] = None
    name: Annotated[str | None, Field(examples=["Utgiftskonto DNB"])] = None
    account_code: Annotated[
        str | None, Field(alias="accountCode", examples=["1920:10007"])
    ] = None
    bank_account_number: Annotated[
        str | None, Field(alias="bankAccountNumber", examples=["15035646830"])
    ] = None
    iban: str | None = None
    bic: str | None = None
    foreign_service: Annotated[str | None, Field(alias="foreignService")] = None
    type: Annotated[Type1 | None, Field(examples=["normal"])] = None
    reconciled_balance: Annotated[
        int | None,
        Field(
            alias="reconciledBalance",
            description="Amounts are always represented as a number, and specifies the number of cents in the amount. Fractions will be ignored. ie. 10050 = 100.50",
            examples=[10050],
        ),
    ] = None
    reconciled_date: Annotated[
        date_aliased | None, Field(alias="reconciledDate", examples=["2018-04-03"])
    ] = None
    inactive: Annotated[bool | None, Field(examples=[False])] = False


class BankBalanceResult(BaseModel):
    source: Annotated[
        str | None,
        Field(
            description="Source of the bank balance information.", examples=["MANUAL"]
        ),
    ] = None
    bank_account_id: Annotated[
        int | None,
        Field(
            alias="bankAccountId",
            description="ID of the bank account this balance belongs to",
            examples=[2747365],
        ),
    ] = None
    bank_account_code: Annotated[
        str | None, Field(alias="bankAccountCode", examples=["1920:10002"])
    ] = None
    date: Annotated[
        date_aliased | None,
        Field(
            description="Date of the bank balance, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    amount: Annotated[
        int | None,
        Field(
            description="Bank balance amount in cents (250000 = 2500.00)",
            examples=[250000],
        ),
    ] = None


class VatType(StrEnum):
    no = "no"
    yearly = "yearly"
    monthly = "monthly"
    bi_monthly = "bi-monthly"


class Company(BaseModel):
    name: Annotated[
        str | None,
        Field(description="Name of company.", examples=["Swagger test company"]),
    ] = None
    slug: Annotated[
        str | None,
        Field(
            description="Formatted name of company. This is the companySlug that should be used in all URLs related to this company.",
            examples=["swagger-test-company"],
        ),
    ] = None
    organization_number: Annotated[
        str | None,
        Field(
            alias="organizationNumber",
            description="Brreg organization number.",
            examples=["123456789"],
        ),
    ] = None
    vat_type: Annotated[VatType | None, Field(alias="vatType")] = None
    address: Address | None = None
    phone_number: Annotated[
        str | None, Field(alias="phoneNumber", examples=["62158537"])
    ] = None
    email: Annotated[str | None, Field(examples=["swaggertestcompany@fiken.gmail"])] = (
        None
    )
    creation_date: Annotated[
        date_aliased | None, Field(alias="creationDate", examples=["2025-01-01"])
    ] = None
    has_api_access: Annotated[
        bool | None, Field(alias="hasApiAccess", examples=[True])
    ] = None
    test_company: Annotated[
        bool | None,
        Field(
            alias="testCompany",
            description="Whether the company is a demo (true) or not",
        ),
    ] = None
    accounting_start_date: Annotated[
        date_aliased | None, Field(alias="accountingStartDate", examples=["2025-01-01"])
    ] = None
    vat_registration_date: Annotated[
        date_aliased | None, Field(alias="vatRegistrationDate", examples=["2025-02-01"])
    ] = None


class ContactNote(BaseModel):
    author: Annotated[str | None, Field(examples=["Betty Boop"])] = None
    note: Annotated[str | None, Field(examples=["Garage 45"])] = None


class Note(BaseModel):
    author: Annotated[str | None, Field(examples=["James Jones"])] = None
    note: Annotated[
        str | None,
        Field(examples=["Invoice sent after telephone conversation with customer"]),
    ] = None


class ContactPerson(BaseModel):
    contact_person_id: Annotated[
        int | None, Field(alias="contactPersonId", examples=[2747365])
    ] = None
    name: Annotated[str, Field(examples=["Betty Boop"])]
    email: Annotated[str, Field(examples=["bb@gmail.com"])]
    phone_number: Annotated[
        str | None, Field(alias="phoneNumber", examples=["98573564"])
    ] = None
    address: Address | None = None


class Counter(BaseModel):
    value: Annotated[
        int | None, Field(description="Current value of the counter", examples=[10000])
    ] = 10000


class CreditNoteLineResult(BaseModel):
    income_account: Annotated[
        str | None,
        Field(
            alias="incomeAccount",
            description="Field is similar to vatType, it defaults to the product's income account. Either the line or the product needs to have an income account set.",
            examples=["3000"],
        ),
    ] = None
    vat_type: Annotated[
        str | None,
        Field(
            alias="vatType",
            description='One of: {"HIGH", "MEDIUM", "LOW", "EXEMPT", "EXEMPT_IMPORT_EXPORT", "EXEMPT_REVERSE", "OUTSIDE", "NONE"}. "HIGH" is the most common.\n',
            examples=["HIGH"],
        ),
    ] = None
    unit_price: Annotated[
        int,
        Field(
            alias="unitPrice",
            description="Net price per unit in invoice currency (in cents).",
            examples=[4550],
        ),
    ]
    quantity: Annotated[
        float, Field(description="Number of units to be invoiced.", examples=[5])
    ]
    discount: Annotated[
        float | None,
        Field(
            description="If field is set, all amounts must be given before the discount is applied. The API will calculate the new totals. Discount value should be a percent with a value between 0 and 100. Decimal values such as 25.5 are also allowed.",
            examples=[25],
        ),
    ] = None
    product_id: Annotated[
        int | None,
        Field(
            alias="productId",
            description="Product Id of product associated with invoice line.",
            examples=[2888156],
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="Description of the invoiced product or service.",
            examples=["Goatskin, with extra-long suede cuffs"],
            max_length=200,
        ),
    ] = None
    comment: Annotated[
        str | None,
        Field(
            description="Additional information to be printed on invoice.",
            examples=["One size fits all"],
            max_length=200,
        ),
    ] = None


class DraftLineRequest(BaseModel):
    text: Annotated[
        str, Field(description="Description of the sale/purchase line.", max_length=200)
    ]
    vat_type: Annotated[
        str,
        Field(
            alias="vatType",
            description="Vat Types for SALES: [NONE, HIGH, MEDIUM, RAW_FISH, LOW, EXEMPT_IMPORT_EXPORT, EXEMPT, OUTSIDE, EXEMPT_REVERSE]\nVat Types for PURCHASES: [NONE, HIGH, MEDIUM, RAW_FISH, LOW, HIGH_DIRECT, HIGH_BASIS, MEDIUM_DIRECT, MEDIUM_BASIS, NONE_IMPORT_BASIS,\nHIGH_FOREIGN_SERVICE_DEDUCTIBLE, HIGH_FOREIGN_SERVICE_NONDEDUCTIBLE, LOW_FOREIGN_SERVICE_DEDUCTIBLE,\nLOW_FOREIGN_SERVICE_NONDEDUCTIBLE, HIGH_PURCHASE_OF_EMISSIONSTRADING_OR_GOLD_DEDUCTIBLE, HIGH_PURCHASE_OF_EMISSIONSTRADING_OR_GOLD_NONDEDUCTIBLE]\n",
        ),
    ]
    income_account: Annotated[
        str,
        Field(
            alias="incomeAccount",
            description="Field is similar to vatType, it defaults to the product's income account. Either the line or the product needs to have an income account set.",
            examples=["3000"],
        ),
    ]
    net: Annotated[
        int,
        Field(
            description="Net amount (in creditNote currency) in cents.",
            examples=[25000],
        ),
    ]
    gross: Annotated[
        int,
        Field(
            description="Gross amount (= net+VAT) (in creditNote currency) in cents.",
            examples=[30000],
        ),
    ]
    project_id: Annotated[int | None, Field(alias="projectId", examples=[2888156])] = (
        None
    )


class FullCreditNoteRequest(BaseModel):
    issue_date: Annotated[
        date_aliased,
        Field(
            alias="issueDate",
            description="Date that the credit note is issued, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ]
    invoice_id: Annotated[
        int,
        Field(
            alias="invoiceId",
            description="Id of invoice that the credit note is associated with.",
            examples=[2888156],
        ),
    ]
    credit_note_text: Annotated[
        str | None,
        Field(
            alias="creditNoteText",
            examples=[
                "Invoice for services rendered during the Oslo Knitting Festival."
            ],
            max_length=500,
        ),
    ] = None


class InboxResult(BaseModel):
    document_id: Annotated[
        int | None, Field(alias="documentId", examples=[1234134])
    ] = None
    name: Annotated[
        str | None, Field(description="Name of the document as it appears in the inbox")
    ] = None
    description: Annotated[
        str | None, Field(description="Additional description of document")
    ] = None
    filename: Annotated[
        str | None,
        Field(description="Name of the underlying file for the inbox document"),
    ] = None
    status: Annotated[
        bool | None,
        Field(description="Whether the document has been used as documentation or not"),
    ] = None
    created_at: Annotated[
        AwareDatetime | None,
        Field(alias="createdAt", description="When the document was created"),
    ] = None


class InvoiceishDraftLine(BaseModel):
    invoiceish_draft_line_id: Annotated[
        int | None,
        Field(
            alias="invoiceishDraftLineId",
            description="Unique draft line ID",
            examples=[2888156],
        ),
    ] = None
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that the draft line was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2018-04-03"],
        ),
    ] = None
    product_id: Annotated[
        int | None,
        Field(
            alias="productId",
            description="Product to be credited/debited on invoice draft line.",
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="Description of the invoiced product or service.",
            examples=["Goatskin, with extra-long suede cuffs"],
            max_length=200,
        ),
    ] = None
    unit_price: Annotated[
        int | None,
        Field(
            alias="unitPrice",
            description="Net price per unit in invoice currency (in cents).",
            examples=[4550],
        ),
    ] = None
    vat_type: Annotated[
        str | None,
        Field(
            alias="vatType",
            description="Vat Types for SALES: [NONE, HIGH, MEDIUM, RAW_FISH, LOW, EXEMPT_IMPORT_EXPORT, EXEMPT, OUTSIDE, EXEMPT_REVERSE]\nVat Types for PURCHASES: [NONE, HIGH, MEDIUM, RAW_FISH, LOW, HIGH_DIRECT, HIGH_BASIS, MEDIUM_DIRECT, MEDIUM_BASIS, NONE_IMPORT_BASIS,\nHIGH_FOREIGN_SERVICE_DEDUCTIBLE, HIGH_FOREIGN_SERVICE_NONDEDUCTIBLE, LOW_FOREIGN_SERVICE_DEDUCTIBLE,\nLOW_FOREIGN_SERVICE_NONDEDUCTIBLE, HIGH_PURCHASE_OF_EMISSIONSTRADING_OR_GOLD_DEDUCTIBLE, HIGH_PURCHASE_OF_EMISSIONSTRADING_OR_GOLD_NONDEDUCTIBLE]\n",
        ),
    ] = None
    quantity: Annotated[
        float, Field(description="Number of units to be invoiced.", examples=[5])
    ]
    discount: Annotated[
        float | None,
        Field(
            description="Percentage discount charged on invoice draft line. Should be a value between 0 and 100. Can be decimal values such as 25.5",
            examples=[25],
        ),
    ] = None
    comment: Annotated[
        str | None,
        Field(
            description="Additional information to be printed on invoice.",
            examples=["One size fits all"],
            max_length=200,
        ),
    ] = None
    income_account: Annotated[
        str | None,
        Field(
            alias="incomeAccount",
            description="Field is similar to vatType, it defaults to the product's income account. Either the line or the product needs to have an income account set.",
            examples=["3000"],
        ),
    ] = None


class Type3(StrEnum):
    invoice = "invoice"
    cash_invoice = "cash_invoice"
    offer = "offer"
    order_confirmation = "order_confirmation"
    credit_note = "credit_note"


class InvoiceishDraftRequest(BaseModel):
    type: Annotated[Type3, Field(description="Type of draft.", examples=["invoice"])]
    uuid: Annotated[
        str | None,
        Field(
            description="UUID are represented as 32 hexadecimal (base-16) digits, displayed in 5 groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters.",
            examples=["123e4567-e89b-12d3-a456-426655440000"],
        ),
    ] = None
    issue_date: Annotated[
        date_aliased | None,
        Field(
            alias="issueDate",
            description="Issue date of the invoice draft, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    days_until_due_date: Annotated[
        int,
        Field(
            alias="daysUntilDueDate",
            description="Days until due date of the invoice draft.",
            examples=[15],
        ),
    ]
    invoice_text: Annotated[
        str | None,
        Field(
            alias="invoiceText",
            description="Comment/description printed above the invoice lines. If not present, and standard text is registered, standard text is printed.",
        ),
    ] = None
    your_reference: Annotated[str | None, Field(alias="yourReference")] = None
    our_reference: Annotated[str | None, Field(alias="ourReference")] = None
    order_reference: Annotated[
        str | None,
        Field(
            alias="orderReference", description="Reference if sending invoice via EHF."
        ),
    ] = None
    lines: list[InvoiceishDraftLine] | None = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ] = None
    bank_account_number: Annotated[
        str | None, Field(alias="bankAccountNumber", examples=["11112233334"])
    ] = None
    iban: str | None = None
    bic: str | None = None
    payment_account: Annotated[
        str | None, Field(alias="paymentAccount", examples=["1920:10001"])
    ] = None
    customer_id: Annotated[
        int,
        Field(
            alias="customerId",
            description="customerId = contactId where customer = true",
            examples=[7340852],
        ),
    ]
    contact_person_id: Annotated[
        int | None,
        Field(
            alias="contactPersonId",
            description="Id of the contact person. Must be associated with the provided customer.",
            examples=[8588156],
        ),
    ] = None
    project_id: Annotated[int | None, Field(alias="projectId", examples=[75408386])] = (
        None
    )


class Type4(StrEnum):
    invoice = "invoice"
    cash_invoice = "cash_invoice"
    offer = "offer"
    order_confirmation = "order_confirmation"
    credit_note = "credit_note"
    repeating_invoice = "repeating_invoice"


class InvoiceLineRequest(BaseModel):
    net: Annotated[
        int | None,
        Field(
            description="Net amount of invoice line in cents in original currency.",
            examples=[4500],
        ),
    ] = None
    vat: Annotated[
        int | None,
        Field(
            description="VAT amount of invoice line in cents in original currency.",
            examples=[500],
        ),
    ] = None
    vat_type: Annotated[
        str | None,
        Field(
            alias="vatType",
            description='Taken from either 1) the line or 2) the product. At least vatType or vatPercent has to be specified. If both are specified, Fiken will assert that the given vat type matches the given vat percent for the issue date.\nOne of: {"HIGH", "MEDIUM", "LOW", "EXEMPT", "EXEMPT_IMPORT_EXPORT", "EXEMPT_REVERSE", "OUTSIDE", "NONE"}. "HIGH" is the most common.\n',
            examples=["HIGH"],
        ),
    ] = None
    gross: Annotated[
        int | None,
        Field(description="Gross amount of invoice line in cents.", examples=[5000]),
    ] = None
    vat_in_percent: Annotated[
        float | None,
        Field(
            alias="vatInPercent",
            description="Percentage value of VAT charged on invoice line. Should be a value between 0 and 100. Can be decimal values such as 25.5",
            examples=[25],
        ),
    ] = None
    unit_price: Annotated[
        int | None,
        Field(
            alias="unitPrice",
            description="Net price per unit in invoice currency (in cents). WARNING - if specified here and different from unitPrice of the product, then this amount overwrites the product price on the invoice.",
            examples=[4550],
        ),
    ] = None
    quantity: Annotated[
        float, Field(description="Number of units to be invoiced.", examples=[5])
    ]
    discount: Annotated[
        float | None,
        Field(
            description="If field is set, all amounts must be given before the discount is applied. The API will calculate the new totals. Discount value should be a value between 0 and 100.",
            examples=[25],
        ),
    ] = None
    product_name: Annotated[
        str | None,
        Field(
            alias="productName",
            description="Name of product to be printed on invoice line. Should only be specified when productId is not provided.",
            examples=["Gardening Gloves VI2"],
        ),
    ] = None
    product_id: Annotated[
        int | None,
        Field(
            alias="productId",
            description="Product Id of product associated with invoice line.",
            examples=[2888156],
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="Description of the invoiced product or service. WARNING - if specified here and different from description of the product, then thisoverwrites the product description on the invoice.",
            examples=["Goatskin, with extra-long suede cuffs"],
            max_length=200,
        ),
    ] = None
    comment: Annotated[
        str | None,
        Field(
            description="Additional information to be printed on invoice.",
            examples=["One size fits all"],
            max_length=200,
        ),
    ] = None
    income_account: Annotated[
        str | None,
        Field(
            alias="incomeAccount",
            description="Field is similar to vatType, it defaults to the product's income account. Either the line or the product needs to have an income account set.\nWARNING - if specified here and different from income account of the product, then this account overwrites the product account on the invoice.\n",
            examples=["3000"],
        ),
    ] = None


class InvoiceLineResult(BaseModel):
    net: Annotated[
        int | None,
        Field(
            description="Net amount of invoice line in cents in original currency.",
            examples=[4500],
        ),
    ] = None
    vat: Annotated[
        int | None,
        Field(
            description="VAT amount of invoice line in cents in original currency.",
            examples=[500],
        ),
    ] = None
    vat_type: Annotated[
        str | None,
        Field(
            alias="vatType",
            description='Taken from either 1) the line or 2) the product. At least vatType or vatPercent has to be specified. If both are specified, Fiken will assert that the given vat type matches the given vat percent for the issue date.\nOne of: {"HIGH", "MEDIUM", "LOW", "EXEMPT", "EXEMPT_IMPORT_EXPORT", "EXEMPT_REVERSE", "OUTSIDE", "NONE"}. "HIGH" is the most common.\n',
            examples=["HIGH"],
        ),
    ] = None
    gross: Annotated[
        int | None,
        Field(description="Gross amount of invoice line in cents.", examples=[5000]),
    ] = None
    net_in_nok: Annotated[
        int | None,
        Field(
            alias="netInNok",
            description="Net amount of invoice line in cents in NOK if currency and amounts provided are in foreign currency. This is calculated by Fiken.",
            examples=[4500],
        ),
    ] = None
    vat_in_nok: Annotated[
        int | None,
        Field(
            alias="vatInNok",
            description="VAT amount of invoice line in cents in NOK if currency and amounts provided are in foreign currency. This is calculated by Fiken.",
            examples=[500],
        ),
    ] = None
    gross_in_nok: Annotated[
        int | None,
        Field(
            alias="grossInNok",
            description="Gross amount of invoice line in cents in NOK if currency and amounts provided are in foreign currency. This is calculated by Fiken.",
            examples=[5000],
        ),
    ] = None
    vat_in_percent: Annotated[
        float | None,
        Field(
            alias="vatInPercent",
            description="Percentage value of VAT charged on invoice line. Should be a value between 0 and 1",
            examples=[25],
        ),
    ] = None
    unit_price: Annotated[
        int | None,
        Field(
            alias="unitPrice",
            description="Net price per unit in invoice currency (in cents).",
            examples=[4550],
        ),
    ] = None
    quantity: Annotated[
        float | None, Field(description="Number of units to be invoiced.", examples=[5])
    ] = None
    discount: Annotated[
        float | None,
        Field(
            description="If field is set, all amounts must be given before the discount is applied. The API will calculate the new totals. Discount value should be a value between 0 and 1.",
            examples=[25],
        ),
    ] = None
    product_id: Annotated[
        int | None,
        Field(
            alias="productId",
            description="Product Id of product associated with invoice line.",
            examples=[2888156],
        ),
    ] = None
    product_name: Annotated[
        str | None,
        Field(
            alias="productName",
            description="Name of product to be printed on invoice line.",
            examples=["Gardening Gloves VI2"],
        ),
    ] = None
    description: Annotated[
        str | None,
        Field(
            description="Description of the invoiced product or service.",
            examples=["Goatskin, with extra-long suede cuffs"],
            max_length=200,
        ),
    ] = None
    comment: Annotated[
        str | None,
        Field(
            description="Additional information to be printed on invoice.",
            examples=["One size fits all"],
            max_length=200,
        ),
    ] = None
    income_account: Annotated[
        str | None,
        Field(
            alias="incomeAccount",
            description="Field is similar to vatType, it defaults to the product's income account. Either the line or the product needs to have an income account set.",
            examples=["3000"],
        ),
    ] = None


class InvoiceRequest(BaseModel):
    uuid: Annotated[
        str | None,
        Field(
            description="UUID are represented as 32 hexadecimal (base-16) digits, displayed in 5 groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters. If not provided, API will generate a UUID.",
            examples=["123e4567-e89b-12d3-a456-426655440000"],
        ),
    ] = None
    issue_date: Annotated[
        date_aliased,
        Field(
            alias="issueDate",
            description="Date that the invoice was issued, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ]
    due_date: Annotated[
        date_aliased,
        Field(
            alias="dueDate",
            description="Due date of invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ]
    lines: Annotated[list[InvoiceLineRequest], Field(min_length=1)]
    our_reference: Annotated[str | None, Field(alias="ourReference")] = None
    your_reference: Annotated[
        str | None,
        Field(
            alias="yourReference",
            description="Your reference for invoice, free string format",
        ),
    ] = None
    order_reference: Annotated[
        str | None,
        Field(alias="orderReference", description="Reference if sending via EHF."),
    ] = None
    customer_id: Annotated[
        int,
        Field(
            alias="customerId",
            description="customerId = contactId where customer = true",
            examples=[2888156],
        ),
    ]
    contact_person_id: Annotated[
        int | None,
        Field(
            alias="contactPersonId",
            description="Id of the contact person. Must be associated with the provided customer.",
            examples=[8588156],
        ),
    ] = None
    bank_account_code: Annotated[
        str,
        Field(
            alias="bankAccountCode",
            description="Bank account code associated with invoice, format 1920:XXXXX",
            examples=["1920:10002"],
        ),
    ]
    currency: Annotated[
        str | None,
        Field(
            description='ISO 4217 currency code. Defaults to "NOK" if unspecified.',
            examples=["NOK"],
            pattern="^[A-Z]{3}$",
        ),
    ] = None
    invoice_text: Annotated[
        str | None,
        Field(
            alias="invoiceText",
            description="If not present, and standard text is registered, standard text is printed.",
            examples=[
                "Invoice for services rendered during the Oslo Knitting Festival."
            ],
            max_length=500,
        ),
    ] = None
    cash: Annotated[
        bool,
        Field(
            description="Payment taken in cash (True) or not (False).", examples=[False]
        ),
    ]
    payment_account: Annotated[
        str | None,
        Field(
            alias="paymentAccount",
            description='For Cash Invoices only. For instance "1920:10001".',
            examples=["1920:10001"],
        ),
    ] = None
    project_id: Annotated[
        int | None,
        Field(
            alias="projectId",
            description="Optional - Associated project for the invoice to be created.",
            examples=[15124866],
        ),
    ] = None


class DispatchType(StrEnum):
    email = "email"
    sms = "sms"
    ehf = "ehf"
    letter = "letter"
    vipps = "vipps"
    efaktura = "efaktura"
    unknown = "unknown"


class DispatchResult(BaseModel):
    date: Annotated[
        date_aliased | None,
        Field(
            description="Date that invoice/offer was sent from Fiken, format yyyy-mm-dd",
            examples=["2024-04-03"],
        ),
    ] = None
    dispatch_type: Annotated[
        DispatchType | None,
        Field(
            alias="dispatchType",
            description="The type of dispatch. Unknown is returned when an invoice/offer was manually sent and Fiken doesn't know the dispatch method. \nOnly possible dispatch types for offer are email, sms, or letter.\n",
            examples=["email"],
        ),
    ] = None


class JournalEntryLine(BaseModel):
    amount: Annotated[
        int,
        Field(
            description="This will be the net amount (excluding VAT) for debitAccount lines and gross amount \n(including VAT) for creditAccount lines. The reason for this difference is due to the \nway Fiken calculates VAT based on the debitVatCode and creditVatCode.\n",
            examples=[310000],
        ),
    ]
    account: Annotated[str | None, Field(examples=["2400:20079"])] = None
    vat_code: Annotated[str | None, Field(alias="vatCode", examples=["1"])] = None
    debit_account: Annotated[str | None, Field(alias="debitAccount")] = None
    debit_vat_code: Annotated[int | None, Field(alias="debitVatCode")] = None
    credit_account: Annotated[str | None, Field(alias="creditAccount")] = None
    credit_vat_code: Annotated[int | None, Field(alias="creditVatCode")] = None
    project_id: Annotated[list[int] | None, Field(alias="projectId")] = None
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that journal entry line was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2018-04-03"],
        ),
    ] = None


class JournalEntry(BaseModel):
    journal_entry_id: Annotated[int | None, Field(alias="journalEntryId")] = None
    created_date: Annotated[
        date_aliased | None,
        Field(
            alias="createdDate",
            description="Date that journal entry was created in Fiken, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that journal entry was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2018-04-03"],
        ),
    ] = None
    transaction_id: Annotated[int | None, Field(alias="transactionId")] = None
    offset_transaction_id: Annotated[
        int | None,
        Field(
            alias="offsetTransactionId",
            description="If a journal entry has been cancelled this provides the id of the balancing transaction",
        ),
    ] = None
    journal_entry_number: Annotated[
        int | None, Field(alias="journalEntryNumber", examples=[18])
    ] = None
    description: Annotated[
        str,
        Field(
            description="We add the flag 'Fri postering registrert via API: '. This must be taken into account in the max length of the description",
            examples=["Purchase, Schweigaards Gate 34 AS (invoice nr 26083)"],
            max_length=200,
        ),
    ]
    date: Annotated[date_aliased, Field(examples=["2018-04-03"])]
    lines: list[JournalEntryLine]
    attachments: list[Attachment] | None = None


class Offer(BaseModel):
    offer_id: Annotated[
        int | None, Field(alias="offerId", description="offer ID", examples=[2888156])
    ] = None
    offer_draft_uuid: Annotated[
        str | None,
        Field(
            alias="offerDraftUuid",
            description="UUID are represented as 32 hexadecimal (base-16) digits, displayed in 5 groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters.",
            examples=["123e4567-e89b-12d3-a456-426655440000"],
        ),
    ] = None
    date: Annotated[
        date_aliased | None,
        Field(description="Date for offer", examples=["2018-04-03"]),
    ] = None
    offer_number: Annotated[
        int | None,
        Field(
            alias="offerNumber",
            description="Unique offer number generated by us.",
            examples=[10001],
        ),
    ] = None
    net: Annotated[
        int | None,
        Field(
            description="Net amount (in invoice currency) in cents.", examples=[25000]
        ),
    ] = None
    vat: Annotated[
        int | None,
        Field(
            description="VAT amount (in invoice currency) in cents.", examples=[5000]
        ),
    ] = None
    gross: Annotated[
        int | None,
        Field(
            description="Gross amount (= net+VAT) (in invoice currency) in cents.",
            examples=[30000],
        ),
    ] = None
    comment: Annotated[str | None, Field(description="Comment/description")] = None
    your_reference: Annotated[str | None, Field(alias="yourReference")] = None
    our_reference: Annotated[str | None, Field(alias="ourReference")] = None
    order_reference: Annotated[
        str | None,
        Field(
            alias="orderReference", description="Reference if sending invoice via EHF."
        ),
    ] = None
    discount: Annotated[
        float | None,
        Field(
            description="The discount amount in the specified currency.",
            examples=[2500],
        ),
    ] = None
    address: Address | None = None
    lines: list[InvoiceLineResult] | None = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code, default value is NOK",
            pattern="^[A-Z]{3}$",
        ),
    ] = "NOK"
    contact_id: Annotated[
        int | None,
        Field(
            alias="contactId",
            description="Contact associated with offer.",
            examples=[9688154],
        ),
    ] = None
    contact_person_id: Annotated[
        int | None,
        Field(
            alias="contactPersonId",
            description="Contact person associated with offer. Must belong to the provided contact.",
            examples=[9688154],
        ),
    ] = None
    project_id: Annotated[int | None, Field(alias="projectId", examples=[2815556])] = (
        None
    )
    archived: Annotated[
        bool | None,
        Field(
            description="If order confirmation has been archived or not.",
            examples=[False],
        ),
    ] = False
    accepted: Annotated[
        date_aliased | None,
        Field(
            description="Date that the offer was accepted. If null, the offer has not been accepted",
            examples=["2025-04-03"],
        ),
    ] = None
    dispatches: list[DispatchResult] | None = None


class OrderConfirmation(BaseModel):
    confirmation_id: Annotated[
        int | None,
        Field(alias="confirmationId", description="offer ID", examples=[2888156]),
    ] = None
    confirmation_draft_uuid: Annotated[
        str | None,
        Field(
            alias="confirmationDraftUuid",
            description="UUID are represented as 32 hexadecimal (base-16) digits, displayed in 5 groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters.",
            examples=["123e4567-e89b-12d3-a456-426655440000"],
        ),
    ] = None
    date: Annotated[
        date_aliased | None,
        Field(description="Date for offer", examples=["2018-04-03"]),
    ] = None
    confirmation_number: Annotated[
        int | None,
        Field(
            alias="confirmationNumber",
            description="Unique offer number generated by us.",
            examples=[10001],
        ),
    ] = None
    net: Annotated[
        int | None,
        Field(
            description="Net amount (in invoice currency) in cents.", examples=[25000]
        ),
    ] = None
    vat: Annotated[
        int | None,
        Field(
            description="VAT amount (in invoice currency) in cents.", examples=[5000]
        ),
    ] = None
    gross: Annotated[
        int | None,
        Field(
            description="Gross amount (= net+VAT) (in invoice currency) in cents.",
            examples=[30000],
        ),
    ] = None
    comment: Annotated[str | None, Field(description="Comment/description")] = None
    your_reference: Annotated[str | None, Field(alias="yourReference")] = None
    our_reference: Annotated[str | None, Field(alias="ourReference")] = None
    order_reference: Annotated[
        str | None,
        Field(
            alias="orderReference", description="Reference if sending invoice via EHF."
        ),
    ] = None
    discount: Annotated[
        float | None,
        Field(
            description="The discount amount in the specified currency.",
            examples=[2500],
        ),
    ] = None
    address: Address | None = None
    lines: list[InvoiceLineResult] | None = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code, default value is NOK",
            pattern="^[A-Z]{3}$",
        ),
    ] = "NOK"
    contact_id: Annotated[
        int | None,
        Field(
            alias="contactId",
            description="Contact associated with offer.",
            examples=[9688154],
        ),
    ] = None
    contact_person_id: Annotated[
        int | None,
        Field(
            alias="contactPersonId",
            description="Contact person associated with the order confirmation. Must belong to given contact.",
            examples=[9688154],
        ),
    ] = None
    project_id: Annotated[int | None, Field(alias="projectId", examples=[2815556])] = (
        None
    )
    created_invoice: Annotated[
        int | None,
        Field(
            alias="createdInvoice",
            description="If the order confirmation was used to create an invoice, the id of the associated invoice. Otherwise null is returned.",
            examples=[2815556],
        ),
    ] = None
    archived: Annotated[
        bool | None,
        Field(
            description="If order confirmation has been archived or not.",
            examples=[False],
        ),
    ] = False
    internal_comment: Annotated[
        str | None,
        Field(
            alias="internalComment",
            description="Comment that is not shown on the order confirmation, but kept for internal use only",
        ),
    ] = None


class OrderLine(BaseModel):
    description: Annotated[
        str, Field(description="Description of the product or service.", max_length=200)
    ]
    net_price: Annotated[
        int | None,
        Field(
            alias="netPrice",
            description="Net amount of order line in cents. Either netPrice or netPriceInCurrency must be provided.",
            examples=[4500],
        ),
    ] = None
    vat: Annotated[
        int | None,
        Field(description="VAT amount of order line in cents.", examples=[500]),
    ] = None
    account: Annotated[
        str | None,
        Field(
            description="Expense account (kostnadskonto) associated with payment.",
            examples=["3000"],
        ),
    ] = None
    vat_type: Annotated[
        str,
        Field(
            alias="vatType",
            description="Vat Types for SALES: [NONE, HIGH, MEDIUM, RAW_FISH, LOW, EXEMPT_IMPORT_EXPORT, EXEMPT, OUTSIDE, EXEMPT_REVERSE]\nVat Types for PURCHASES: [NONE, HIGH, MEDIUM, RAW_FISH, LOW, HIGH_DIRECT, HIGH_BASIS, MEDIUM_DIRECT, MEDIUM_BASIS, NONE_IMPORT_BASIS,\nHIGH_FOREIGN_SERVICE_DEDUCTIBLE, HIGH_FOREIGN_SERVICE_NONDEDUCTIBLE, LOW_FOREIGN_SERVICE_DEDUCTIBLE,\nLOW_FOREIGN_SERVICE_NONDEDUCTIBLE, HIGH_PURCHASE_OF_EMISSIONSTRADING_OR_GOLD_DEDUCTIBLE, HIGH_PURCHASE_OF_EMISSIONSTRADING_OR_GOLD_NONDEDUCTIBLE]\n",
        ),
    ]
    net_price_in_currency: Annotated[
        int | None,
        Field(
            alias="netPriceInCurrency",
            description="Net amount in currency (in cents)",
            examples=[4500],
        ),
    ] = None
    vat_in_currency: Annotated[
        int | None,
        Field(
            alias="vatInCurrency",
            description="VAT amount in currency (in cents)",
            examples=[500],
        ),
    ] = None
    project_id: Annotated[
        int | None,
        Field(
            alias="projectId",
            description="If a purchase is split over several projects, project/line can be specified. This field is only to be used for purchases.",
            examples=[2815556],
        ),
    ] = None


class PartialCreditNoteRequest(BaseModel):
    our_reference: Annotated[
        str | None, Field(alias="ourReference", description="Optional")
    ] = None
    your_reference: Annotated[
        str | None,
        Field(
            alias="yourReference",
            description="Optional - Your reference for invoice, free string format.",
        ),
    ] = None
    order_reference: Annotated[
        str | None,
        Field(alias="orderReference", description="Reference if sending via EHF."),
    ] = None
    project: Annotated[
        int | None,
        Field(description="Optional - Project associated with the credit note."),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ] = None
    issue_date: Annotated[
        date_aliased,
        Field(
            alias="issueDate",
            description="Date that the credit note is issued, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ]
    invoice_id: Annotated[
        int | None,
        Field(
            alias="invoiceId",
            description="Optional - Id of invoice that the credit note is associated with.",
            examples=[2888156],
        ),
    ] = None
    contact_id: Annotated[
        int | None,
        Field(
            alias="contactId",
            description="Id of contact that the credit note is associated with.",
            examples=[3588152],
        ),
    ] = None
    contact_person_id: Annotated[
        int | None,
        Field(
            alias="contactPersonId",
            description="Id of contact person that the credit note is associated with (Credit person must belong to the provided contact).",
            examples=[3588152],
        ),
    ] = None
    credit_note_text: Annotated[
        str | None,
        Field(
            alias="creditNoteText",
            examples=[
                "Invoice for services rendered during the Oslo Knitting Festival."
            ],
            max_length=500,
        ),
    ] = None
    lines: list[CreditNoteLineResult]


class Payment(BaseModel):
    payment_id: Annotated[
        int | None,
        Field(
            alias="paymentId", description="Id of given payment.", examples=[2888156]
        ),
    ] = None
    date: Annotated[
        date_aliased,
        Field(description="Payment date, format yyyy-mm-dd", examples=["2018-04-03"]),
    ]
    account: Annotated[
        str,
        Field(description="Account associated with payment.", examples=["1920:10001"]),
    ]
    amount: Annotated[
        int,
        Field(
            description='Amount paid in the specified currency. If no currency is provided then currency defaults to "NOK". Formatted in cents (34000 = 340.00)',
            examples=[34000],
        ),
    ]
    amount_in_nok: Annotated[
        int | None,
        Field(
            alias="amountInNok",
            description="Attribute of a foreign payment only. Is required if amount is provided in currency other than NOK and should be the actual amount \nthat was received in the bank account. Fiken calculates the value based on the exchange rate for the given date if no amountInNok is sent. \nFormatted in cents (500000 = 5000.00)\n",
            examples=[500000],
        ),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description='Only specify the currency if other than "NOK", otherwise default currency is "NOK". ISO 4217 currency code',
            examples=["NOK"],
            pattern="^[A-Z]{3}$",
        ),
    ] = None
    fee: Annotated[
        int | None,
        Field(
            description='Any fees additional to the amount paid in the specified currency. This is always a "NOK" amount even if the sale currency is a different currency.'
        ),
    ] = None


class Product(BaseModel):
    product_id: Annotated[
        int | None,
        Field(alias="productId", description="Product Id.", examples=[2888156]),
    ] = None
    created_date: Annotated[
        date_aliased | None,
        Field(
            alias="createdDate",
            description="Date that product was created in Fiken, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that product was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2018-04-03"],
        ),
    ] = None
    name: Annotated[str, Field(description="Product name.", examples=["Spade"])]
    unit_price: Annotated[
        int | None,
        Field(
            alias="unitPrice",
            description="The net unit price in cents.",
            examples=[300000],
        ),
    ] = None
    income_account: Annotated[
        str,
        Field(
            alias="incomeAccount",
            description="The accounting account that will receive the payment.",
            examples=["3000"],
        ),
    ]
    vat_type: Annotated[
        str,
        Field(
            alias="vatType",
            description='One of {"HIGH", "MEDIUM", "LOW", "EXEMPT", "EXEMPT_IMPORT_EXPORT", "EXEMPT_REVERSE", "OUTSIDE", "NONE"}. "HIGH" is the most common.',
            examples=["HIGH"],
        ),
    ]
    active: Annotated[
        bool | None,
        Field(
            description="If product is in use (True) or not (False).", examples=[True]
        ),
    ] = True
    product_number: Annotated[
        str | None, Field(alias="productNumber", examples=["125-1"])
    ] = None
    stock: Annotated[
        float | None,
        Field(
            description="Number of products available in stock. If not provided, stock value is set to null. Decimal values are accepted. For example 5.5",
            examples=[5],
        ),
    ] = None
    note: Annotated[
        str | None,
        Field(description="Optional field for additional information.", max_length=200),
    ] = None


class ProductSalesLineInfo(BaseModel):
    count: Annotated[int | None, Field(examples=[250])] = None
    sales: Annotated[int | None, Field(examples=[45])] = None
    net_amount: Annotated[
        int | None,
        Field(
            alias="netAmount",
            description="Net amount excluding VAT in cents (5000 = 50.00)",
            examples=[5000],
        ),
    ] = None
    vat_amount: Annotated[
        int | None,
        Field(
            alias="vatAmount",
            description="VAT amount for sale in cents (500 = 5.00)",
            examples=[500],
        ),
    ] = None
    gross_amount: Annotated[
        int | None,
        Field(
            alias="grossAmount",
            description="Gross amount of sale (net + VAT) in cents (5500 = 55.00)",
            examples=[5500],
        ),
    ] = None


class ProductSalesReportRequest(BaseModel):
    from_: Annotated[
        date_aliased,
        Field(
            alias="from",
            description="Start date range for the report, inclusive, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ]
    to: Annotated[
        date_aliased,
        Field(
            description="End date range for the report, inclusive, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ]


class ProductSalesReportResult(BaseModel):
    product: Product | None = None
    sold: ProductSalesLineInfo | None = None
    credited: ProductSalesLineInfo | None = None
    sum: ProductSalesLineInfo | None = None


class ProjectRequest(BaseModel):
    number: str
    name: str
    description: str | None = None
    start_date: Annotated[
        date_aliased,
        Field(
            alias="startDate",
            description="Start date for the project, inclusive, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ]
    end_date: Annotated[
        date_aliased | None,
        Field(
            alias="endDate",
            description="End date for the project, inclusive, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    contact_id: Annotated[int | None, Field(alias="contactId", examples=[73408306])] = (
        None
    )
    completed: Annotated[
        bool | None, Field(description="Whether the project is completed or not.")
    ] = None


class Kind(StrEnum):
    cash_purchase = "cash_purchase"
    supplier = "supplier"


class PurchaseRequest(BaseModel):
    transaction_id: Annotated[
        int | None, Field(alias="transactionId", examples=[3458156])
    ] = None
    identifier: Annotated[
        str | None, Field(description="Invoice/sale number or similar.")
    ] = None
    date: Annotated[
        date_aliased,
        Field(description="Payment date, format yyyy-mm-dd", examples=["2018-04-03"]),
    ]
    due_date: Annotated[
        date_aliased | None,
        Field(
            alias="dueDate",
            description="Due date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    kind: Annotated[
        Kind,
        Field(
            description="Purchased with cash or through a supplier.",
            examples=["cash_purchase"],
        ),
    ]
    lines: list[OrderLine]
    supplier_id: Annotated[
        int | None,
        Field(
            alias="supplierId",
            description="Id of supplier if not a cash purchase.",
            examples=[2888156],
        ),
    ] = None
    currency: Annotated[
        str,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ]
    payment_account: Annotated[
        str | None, Field(alias="paymentAccount", examples=["1920:10001"])
    ] = None
    payment_date: Annotated[
        date_aliased | None,
        Field(
            alias="paymentDate",
            description="Payment date, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    kid: Annotated[
        str | None,
        Field(
            description="Norwegian KID number. Number from 2 to 25 digits long.",
            examples=["5855454756"],
        ),
    ] = None
    project_id: Annotated[
        int | None,
        Field(
            alias="projectId", description="Id of given project.", examples=[2888156]
        ),
    ] = None


class Kind2(StrEnum):
    cash_sale = "cash_sale"
    invoice = "invoice"
    external_invoice = "external_invoice"


class SaleRequest(BaseModel):
    sale_number: Annotated[
        str | None,
        Field(
            alias="saleNumber", description="Identifier for sale.", examples=["XK455L"]
        ),
    ] = None
    date: Annotated[
        date_aliased,
        Field(
            description="Date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ]
    kind: Annotated[
        Kind2,
        Field(
            description="Either cash_sale, invoice, or external_invoice.",
            examples=["external_invoice"],
        ),
    ]
    total_paid: Annotated[
        int | None,
        Field(
            alias="totalPaid", description="Total amount paid in NOK", examples=[524500]
        ),
    ] = None
    total_paid_in_currency: Annotated[
        int | None,
        Field(
            alias="totalPaidInCurrency",
            description="Total amount paid in other currency.",
            examples=[634550],
        ),
    ] = None
    lines: list[OrderLine]
    customer_id: Annotated[
        int | None,
        Field(
            alias="customerId",
            description="customerId = contactId where customer = true",
        ),
    ] = None
    currency: Annotated[
        str,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ]
    due_date: Annotated[
        date_aliased | None,
        Field(
            alias="dueDate",
            description="Due date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    kid: Annotated[
        str | None,
        Field(
            description="Norwegian KID number. Number from 2 to 25 digits long.",
            examples=["5855454756"],
        ),
    ] = None
    payment_account: Annotated[
        str | None, Field(alias="paymentAccount", examples=["1920:10001"])
    ] = None
    payment_date: Annotated[
        date_aliased | None,
        Field(
            alias="paymentDate",
            description="Payment date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    payment_fee: Annotated[
        int | None,
        Field(
            alias="paymentFee",
            description="Fee associated with payment of sale.",
            examples=[634550],
        ),
    ] = None
    project_id: Annotated[
        int | None,
        Field(
            alias="projectId", description="Id of given project.", examples=[2888156]
        ),
    ] = None


class MethodEnum(StrEnum):
    email = "email"
    ehf = "ehf"
    efaktura = "efaktura"
    sms = "sms"
    letter = "letter"
    auto = "auto"


class EmailSendOption(StrEnum):
    document_link = "document_link"
    attachment = "attachment"
    auto = "auto"


class SendInvoiceishRequest(BaseModel):
    method: Annotated[
        list[MethodEnum],
        Field(
            description='The method of sending. Has to be auto, email, ehf, efaktura, sms or letter.\nIf several methods are provided they should be in prioritized order as Fiken will only send the invoice to \nthe first successful available method. Method "auto" tries available methods for given customer based on\nthe information registered for the customer. The order of priority is EHF, eFaktura, Sms, and email.\nMethod "letter" means physical letter, printed and sent by our postal service partner (extra charge per\nletter, available for recipient addresses in Norway only). The option "includeDocumentAttachments" is\nnot supported by method "letter", attachments are not included even if this option is set.\n',
            examples=[["sms", "email"]],
        ),
    ]
    include_document_attachments: Annotated[
        bool | None,
        Field(
            alias="includeDocumentAttachments",
            description="Whether the document's attachment should be included when sending (True) or not (False).",
        ),
    ] = True
    recipient_name: Annotated[
        str | None, Field(alias="recipientName", examples=["Bjørn Bohler"])
    ] = None
    recipient_email: Annotated[
        str | None, Field(alias="recipientEmail", examples=["bjorn.bohler@gmail.com"])
    ] = None
    message: Annotated[
        str | None,
        Field(
            description="Additional message to send with document.",
            examples=["Due upon receipt"],
        ),
    ] = None
    email_send_option: Annotated[
        EmailSendOption | None,
        Field(
            alias="emailSendOption",
            description="document_link, attachment or auto. Defaults to auto which uses customer/company settings.",
            examples=["document_link"],
        ),
    ] = EmailSendOption.auto
    merge_invoice_and_attachments: Annotated[
        bool | None,
        Field(
            alias="mergeInvoiceAndAttachments",
            description="If sending with emailSendOption = attachment, this merges them into a single document if true.",
        ),
    ] = False
    organization_number: Annotated[
        str | None,
        Field(
            alias="organizationNumber",
            description="Brreg organization number. Defaults to the customers organization number if not provided.",
            examples=["913312465"],
        ),
    ] = None
    mobile_number: Annotated[
        str | None,
        Field(
            alias="mobileNumber",
            description="Defaults to the customers phone number. Format should include the country code. If a Norwegian phone number, the country code is not necessary.",
            examples=["85262741"],
        ),
    ] = None


class SendCreditNoteRequest(SendInvoiceishRequest):
    credit_note_id: Annotated[
        int,
        Field(
            alias="creditNoteId",
            description="Id of credit note to send.",
            examples=[2888156],
        ),
    ]


class SendInvoiceRequest(SendInvoiceishRequest):
    invoice_id: Annotated[
        int,
        Field(
            alias="invoiceId", description="Id of invoice to send.", examples=[2888156]
        ),
    ]


class Transaction(BaseModel):
    transaction_id: Annotated[
        int | None, Field(alias="transactionId", examples=[734083065])
    ] = None
    created_date: Annotated[
        date_aliased | None,
        Field(
            alias="createdDate",
            description="Date that product was created in Fiken, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that product was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2018-04-03"],
        ),
    ] = None
    description: str | None = None
    type: Annotated[str | None, Field(examples=["General Journal Entry"])] = None
    entries: list[JournalEntry] | None = None
    deleted: Annotated[
        bool | None,
        Field(
            description="If the transaction has been deleted, this field will be true. A deletion creates a reverse transaction to null out the original.",
            examples=[False],
        ),
    ] = None


class UpdateInvoiceRequest(BaseModel):
    new_due_date: Annotated[
        date_aliased | None,
        Field(
            alias="newDueDate",
            description="Due date of invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    sent_manually: Annotated[
        bool | None,
        Field(
            alias="sentManually",
            description='If the invoice was not sent using Fiken this can be set to "true"',
            examples=[True],
        ),
    ] = None


class UpdateProjectRequest(BaseModel):
    name: str | None = None
    description: str | None = None
    start_date: Annotated[
        date_aliased | None,
        Field(
            alias="startDate",
            description="Start date for the project, inclusive, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    end_date: Annotated[
        date_aliased | None,
        Field(
            alias="endDate",
            description="End date for the project, inclusive, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    contact_id: Annotated[int | None, Field(alias="contactId", examples=[73408306])] = (
        None
    )
    completed: Annotated[
        bool | None, Field(description="Whether the project is completed or not.")
    ] = None


class Userinfo(BaseModel):
    name: Annotated[
        str | None, Field(description="Name of the user.", examples=["Test Testesen"])
    ] = None
    email: Annotated[
        str | None,
        Field(description="Users email address.", examples=["test@fiken.no"]),
    ] = None


class AccountBalance(Account):
    balance: Annotated[
        int | None,
        Field(
            description="Balance of account for a given date given in cents (5050 = 50.50)",
            examples=[15200],
        ),
    ] = None


class Contact(BaseModel):
    contact_id: Annotated[int | None, Field(alias="contactId", examples=[2747365])] = (
        None
    )
    created_date: Annotated[
        date_aliased | None,
        Field(
            alias="createdDate",
            description="Date that contact was created in Fiken, format yyyy-mm-dd.",
            examples=["2018-04-03"],
        ),
    ] = None
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that contact was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2018-04-03"],
        ),
    ] = None
    name: Annotated[str, Field(examples=["Fiken AS"], max_length=200, min_length=1)]
    email: Annotated[
        str | None, Field(examples=["kontakt@fiken.gmail"], max_length=200)
    ] = None
    organization_number: Annotated[
        str | None,
        Field(
            alias="organizationNumber",
            description="Brreg organization number.",
            examples=["913312465"],
            max_length=200,
        ),
    ] = None
    customer_number: Annotated[
        int | None, Field(alias="customerNumber", examples=[51248])
    ] = None
    customer_account_code: Annotated[
        str | None,
        Field(
            alias="customerAccountCode",
            description="Format 1500:XXXXX",
            examples=["1500:20001"],
        ),
    ] = None
    phone_number: Annotated[
        str | None, Field(alias="phoneNumber", examples=["62158537"], max_length=20)
    ] = None
    member_number: Annotated[
        float | None,
        Field(
            alias="memberNumber",
            description="A number that can be used to connect a contact to your own data. This field is no longer used and instead memberNumberString should be used.",
            examples=[5464],
        ),
    ] = None
    member_number_string: Annotated[
        str | None,
        Field(
            alias="memberNumberString",
            description="A number/id that can be used to connect a contact to your own data.",
            examples=["5464"],
        ),
    ] = None
    supplier_number: Annotated[int | None, Field(alias="supplierNumber")] = None
    supplier_account_code: Annotated[
        str | None,
        Field(
            alias="supplierAccountCode",
            description="Format 2400:XXXXX",
            examples=["2400:20001"],
        ),
    ] = None
    customer: Annotated[
        bool | None,
        Field(
            description="True if the contact is a customer. It is possible for a contact to be both customer and supplier."
        ),
    ] = False
    supplier: Annotated[
        bool | None,
        Field(
            description="True if the contact is a supplier. It is possible for a contact to be both supplier and customer."
        ),
    ] = False
    bank_account_number: Annotated[
        str | None,
        Field(alias="bankAccountNumber", examples=["11112233334"], max_length=11),
    ] = None
    contact_person: Annotated[
        list[ContactPerson] | None, Field(alias="contactPerson")
    ] = None
    notes: list[ContactNote] | None = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code. Default foreign currency to use when creating invoice to this contact (USD, EUR, SEK etc)",
            examples=["NOK"],
            pattern="^[A-Z]{3}$",
        ),
    ] = None
    language: Annotated[
        str | None,
        Field(
            description="The language to use when sending documents to this contact. NORWEGIAN or ENGLISH. Defaults to NORWEGIAN.",
            examples=["Norwegian"],
        ),
    ] = None
    inactive: Annotated[
        bool | None,
        Field(
            description="Whether the contact has been deactivated (true) or is active (false)",
            examples=[True],
        ),
    ] = None
    days_until_invoicing_due_date: Annotated[
        int | None,
        Field(
            alias="daysUntilInvoicingDueDate",
            description="Default number of days until due date for invoices.",
            examples=[15],
        ),
    ] = None
    discount: Annotated[
        float | None,
        Field(
            description="Discount value should be a percent with a value between 0 and 100. \nDecimal values such as 25.5 are also allowed.\n",
            examples=[25],
        ),
    ] = None
    address: Address | None = None
    groups: list[str] | None = None
    documents: list[Attachment] | None = None


class DraftRequest(BaseModel):
    invoice_issue_date: Annotated[
        date_aliased | None,
        Field(
            alias="invoiceIssueDate",
            description="Issue date of the draft, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    due_date: Annotated[
        date_aliased | None,
        Field(
            alias="dueDate",
            description="Due date of draft, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    invoice_number: Annotated[
        str | None,
        Field(
            alias="invoiceNumber",
            description="If invoice associated with draft, this is the invoice number (not to be confused with the invoiceId of an invoice issued from Fiken)",
            examples=["NOEE2888156"],
        ),
    ] = None
    contact_id: Annotated[
        int | None,
        Field(alias="contactId", description="Contact Id", examples=[2888156]),
    ] = None
    project_id: Annotated[
        int | None,
        Field(
            alias="projectId",
            description="Project ID if only 1 project associated with entire draft. It is also possible to specify the project on individual draft lines",
            examples=[2888156],
        ),
    ] = None
    cash: Annotated[
        bool, Field(description="If a cash sale/purchase (true) or otherwise (false)")
    ]
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ] = None
    kid: Annotated[
        str | None,
        Field(
            description="Norwegian KID number. Number from 2 to 25 digits long.",
            examples=["5855454756"],
        ),
    ] = None
    paid: Annotated[
        bool | None,
        Field(
            description="Whether the sale/purchase has been paid (true) or not (false)"
        ),
    ] = None
    payments: list[Payment] | None = None
    lines: list[DraftLineRequest]


class GeneralJournalEntryRequest(BaseModel):
    description: Annotated[
        str | None,
        Field(
            description="We add the flag 'Fri postering registrert via API: '. This must be taken into account in the max length of the description",
            max_length=200,
        ),
    ] = None
    open: Annotated[
        bool | None,
        Field(
            description="The journal entry can be set to either open or closed (closed is the default). In the case of an open journal entry these can be deleted without creating a counter transaction.",
            examples=[False],
        ),
    ] = False
    journal_entries: Annotated[list[JournalEntry], Field(alias="journalEntries")]


class InvoiceishDraftResult(BaseModel):
    draft_id: Annotated[
        int | None,
        Field(alias="draftId", description="Invoice draft ID", examples=[2888156]),
    ] = None
    uuid: Annotated[
        str | None,
        Field(
            description="UUID are represented as 32 hexadecimal (base-16) digits, displayed in 5 groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters.",
            examples=["123e4567-e89b-12d3-a456-426655440000"],
        ),
    ] = None
    type: Annotated[
        Type4 | None, Field(description="Type of invoice draft.", examples=["invoice"])
    ] = Type4.invoice
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that the draft was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2023-04-03"],
        ),
    ] = None
    issue_date: Annotated[
        date_aliased | None,
        Field(
            alias="issueDate",
            description="Issue date of the invoice draft, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    days_until_due_date: Annotated[
        int | None,
        Field(
            alias="daysUntilDueDate",
            description="Days until due date of the invoice draft.",
            examples=[15],
        ),
    ] = None
    invoice_text: Annotated[
        str | None,
        Field(
            alias="invoiceText",
            description="Comment/description printed above the invoice lines",
        ),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ] = None
    your_reference: Annotated[str | None, Field(alias="yourReference")] = None
    our_reference: Annotated[str | None, Field(alias="ourReference")] = None
    order_reference: Annotated[
        str | None,
        Field(
            alias="orderReference", description="Reference if sending invoice via EHF."
        ),
    ] = None
    lines: list[InvoiceishDraftLine] | None = None
    net: Annotated[
        int | None,
        Field(
            description="The net amount to be invoiced in the specified currency.",
            examples=[4500],
        ),
    ] = None
    gross: Annotated[
        int | None,
        Field(
            description="The gross amount to be invoiced in the specified currency.",
            examples=[5000],
        ),
    ] = None
    bank_account_number: Annotated[
        str | None, Field(alias="bankAccountNumber", examples=["11112233334"])
    ] = None
    iban: str | None = None
    bic: str | None = None
    payment_account: Annotated[
        str | None, Field(alias="paymentAccount", examples=["1920:10001"])
    ] = None
    customers: Annotated[
        list[Contact] | None,
        Field(description="Customer(s) to be invoiced.", min_length=1),
    ] = None
    attachments: list[Attachment] | None = None
    created_from_invoice_id: Annotated[
        int | None, Field(alias="createdFromInvoiceId", examples=[73408306])
    ] = None
    project_id: Annotated[int | None, Field(alias="projectId", examples=[73408306])] = (
        None
    )


class ProjectResult(BaseModel):
    project_id: Annotated[int | None, Field(alias="projectId", examples=[73408306])] = (
        None
    )
    number: str | None = None
    name: str | None = None
    description: str | None = None
    start_date: Annotated[
        date_aliased | None,
        Field(
            alias="startDate",
            description="Start date for the project, inclusive, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    end_date: Annotated[
        date_aliased | None,
        Field(
            alias="endDate",
            description="End date for the project, inclusive, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    contact: Contact | None = None
    completed: Annotated[
        bool | None, Field(description="Whether the project is completed or not.")
    ] = None


class PurchaseResult(BaseModel):
    purchase_id: Annotated[
        int | None,
        Field(
            alias="purchaseId", description="Id of given purchase.", examples=[2888156]
        ),
    ] = None
    transaction_id: Annotated[
        int | None, Field(alias="transactionId", examples=[3458156])
    ] = None
    identifier: Annotated[
        str | None, Field(description="Invoice/sale number or similar.")
    ] = None
    date: Annotated[
        date_aliased,
        Field(description="Payment date, format yyyy-mm-dd", examples=["2018-04-03"]),
    ]
    due_date: Annotated[
        date_aliased | None,
        Field(
            alias="dueDate",
            description="Due date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    kind: Annotated[
        Kind,
        Field(
            description="Purchased with cash or through a supplier.",
            examples=["cash_purchase"],
        ),
    ]
    paid: Annotated[bool, Field(examples=[True])]
    lines: list[OrderLine]
    supplier: Contact | None = None
    currency: Annotated[
        str,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ]
    payment_account: Annotated[
        str | None, Field(alias="paymentAccount", examples=["1920:10001"])
    ] = None
    payment_date: Annotated[
        date_aliased | None,
        Field(
            alias="paymentDate",
            description="Payment date, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    payments: list[Payment] | None = None
    purchase_attachments: Annotated[
        list[Attachment] | None, Field(alias="purchaseAttachments")
    ] = None
    kid: Annotated[
        str | None,
        Field(
            description="Norwegian KID number. Number from 2 to 25 digits long.",
            examples=["5855454756"],
        ),
    ] = None
    project: list[ProjectResult] | None = None
    deleted: Annotated[
        bool | None, Field(description="Whether the purchase has been deleted or not")
    ] = None
    settled: Annotated[
        bool | None,
        Field(
            description="If the purchase as been marked as settled (True) or not (False).",
            examples=[True],
        ),
    ] = None
    settled_date: Annotated[
        date_aliased | None,
        Field(
            alias="settledDate",
            description="Date the the purchase was marked as settled, format yyyy-mm-dd",
            examples=["2024-04-03"],
        ),
    ] = None


class SaleResult(BaseModel):
    sale_id: Annotated[
        int | None, Field(alias="saleId", description="Sale Id", examples=[2888156])
    ] = None
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that the sale was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2018-04-03"],
        ),
    ] = None
    transaction_id: Annotated[
        int | None, Field(alias="transactionId", examples=[3458156])
    ] = None
    sale_number: Annotated[
        str | None,
        Field(
            alias="saleNumber", description="Identifier for sale.", examples=["XK455L"]
        ),
    ] = None
    date: Annotated[
        date_aliased | None,
        Field(
            description="Due date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    kind: Annotated[
        Kind2 | None,
        Field(
            description="Either cash_sale, invoice, or external_invoice.",
            examples=["external_invoice"],
        ),
    ] = None
    net_amount: Annotated[
        int | None,
        Field(
            alias="netAmount",
            description="Total net amount of the sale to be paid.",
            examples=[4500],
        ),
    ] = None
    vat_amount: Annotated[
        int | None,
        Field(alias="vatAmount", description="VAT amount on sale.", examples=[5400]),
    ] = None
    settled: Annotated[
        bool | None,
        Field(
            description="If the sale as been marked as settled (True) or not (False).",
            examples=[True],
        ),
    ] = None
    settled_date: Annotated[
        date_aliased | None,
        Field(
            alias="settledDate",
            description="Date the the sale was marked as settled, format yyyy-mm-dd",
            examples=["2023-04-03"],
        ),
    ] = None
    write_off: Annotated[
        bool | None,
        Field(
            alias="writeOff",
            description="If a loss has been registered for this sale (tapsføring av salg).",
            examples=[False],
        ),
    ] = None
    total_paid: Annotated[
        int | None,
        Field(
            alias="totalPaid", description="Total amount paid in NOK", examples=[524500]
        ),
    ] = None
    total_paid_in_currency: Annotated[
        int | None,
        Field(
            alias="totalPaidInCurrency",
            description="Total amount paid in other currency.",
            examples=[634550],
        ),
    ] = None
    outstanding_balance: Annotated[
        int | None, Field(alias="outstandingBalance", examples=[145])
    ] = None
    outstanding_balance_in_currency: Annotated[
        int | None,
        Field(
            alias="outstandingBalanceInCurrency",
            description="Outstanding balance in other currency.",
            examples=[65],
        ),
    ] = None
    lines: list[OrderLine] | None = None
    customer: Contact | None = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ] = None
    due_date: Annotated[
        date_aliased | None,
        Field(
            alias="dueDate",
            description="Due date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    kid: Annotated[
        str | None,
        Field(
            description="Norwegian KID number. Number from 2 to 25 digits long.",
            examples=["5855454756"],
        ),
    ] = None
    payment_account: Annotated[
        str | None, Field(alias="paymentAccount", examples=["1920:10001"])
    ] = None
    sale_payments: Annotated[list[Payment] | None, Field(alias="salePayments")] = None
    sale_attachments: Annotated[
        list[Attachment] | None, Field(alias="saleAttachments")
    ] = None
    payment_date: Annotated[
        date_aliased | None,
        Field(
            alias="paymentDate",
            description="Payment date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    project: ProjectResult | None = None
    notes: list[Note] | None = None
    deleted: Annotated[
        bool | None, Field(description="Whether the sale has been deleted or not")
    ] = None


class CreditNoteResult(BaseModel):
    credit_note_id: Annotated[
        int,
        Field(
            alias="creditNoteId", description="Id of credit note", examples=[2888156]
        ),
    ]
    credit_note_number: Annotated[
        int,
        Field(
            alias="creditNoteNumber",
            description="Unique credit note number generated by us.",
            examples=[10001],
        ),
    ]
    kid: Annotated[
        str | None,
        Field(
            description="Norwegian KID number. Number from 2 to 25 digits long.",
            examples=["5855454756"],
        ),
    ] = None
    customer: Contact
    net: Annotated[
        int,
        Field(
            description="Net amount (in creditNote currency) in cents.",
            examples=[25000],
        ),
    ]
    vat: Annotated[
        int,
        Field(
            description="VAT amount (in creditNote currency) in cents.", examples=[5000]
        ),
    ]
    gross: Annotated[
        int,
        Field(
            description="Gross amount (= net+VAT) (in creditNote currency) in cents.",
            examples=[30000],
        ),
    ]
    net_in_nok: Annotated[
        int,
        Field(
            alias="netInNok",
            description="Net amount in NOK (in cents)",
            examples=[25000],
        ),
    ]
    vat_in_nok: Annotated[
        int,
        Field(
            alias="vatInNok",
            description="VAT amount in NOK (in cents)",
            examples=[5000],
        ),
    ]
    gross_in_nok: Annotated[
        int,
        Field(
            alias="grossInNok",
            description="Gross amount in NOK (in cents)",
            examples=[30000],
        ),
    ]
    credit_note_text: Annotated[
        str | None,
        Field(
            alias="creditNoteText",
            description="Comment/description printed above the credit note lines.",
        ),
    ] = None
    your_reference: Annotated[str | None, Field(alias="yourReference")] = None
    our_reference: Annotated[str | None, Field(alias="ourReference")] = None
    order_reference: Annotated[
        str | None,
        Field(alias="orderReference", description="Reference if sending via EHF."),
    ] = None
    address: Address
    lines: list[InvoiceLineResult] | None = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ] = None
    issue_date: Annotated[
        date_aliased | None,
        Field(
            alias="issueDate",
            description="Issue date of the credit note, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that the credit note was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2024-04-03"],
        ),
    ] = None
    settled: Annotated[
        bool | None,
        Field(
            description="If the credit note as been marked as settled (True) or not (False).",
            examples=[True],
        ),
    ] = None
    associated_invoice_id: Annotated[
        int | None,
        Field(
            alias="associatedInvoiceId",
            description="Id of associated invoice",
            examples=[2888156],
        ),
    ] = None
    credit_note_draft_uuid: Annotated[
        str | None,
        Field(
            alias="creditNoteDraftUuid",
            description="The UUID of the credit note draft used to create the credit note. \nCredit notes created directly from invoices (POST / creditNotes/full and POST /creditNotes/partial) \nwill not have a draft uuid as no draft is created in this case.\n",
            examples=["123e4567-e89b-12d3-a456-426655440000"],
        ),
    ] = None
    credit_note_pdf: Annotated[Attachment | None, Field(alias="creditNotePdf")] = None
    project: ProjectResult | None = None
    sale: SaleResult | None = None


class DraftLineResult(BaseModel):
    text: Annotated[
        str | None,
        Field(description="Description of the sale/purchase line.", max_length=200),
    ] = None
    vat_type: Annotated[
        str | None,
        Field(
            alias="vatType",
            description="Vat Types for SALES: [NONE, HIGH, MEDIUM, RAW_FISH, LOW, EXEMPT_IMPORT_EXPORT, EXEMPT, OUTSIDE, EXEMPT_REVERSE]\nVat Types for PURCHASES: [NONE, HIGH, MEDIUM, RAW_FISH, LOW, HIGH_DIRECT, HIGH_BASIS, MEDIUM_DIRECT, MEDIUM_BASIS, NONE_IMPORT_BASIS,\nHIGH_FOREIGN_SERVICE_DEDUCTIBLE, HIGH_FOREIGN_SERVICE_NONDEDUCTIBLE, LOW_FOREIGN_SERVICE_DEDUCTIBLE,\nLOW_FOREIGN_SERVICE_NONDEDUCTIBLE, HIGH_PURCHASE_OF_EMISSIONSTRADING_OR_GOLD_DEDUCTIBLE, HIGH_PURCHASE_OF_EMISSIONSTRADING_OR_GOLD_NONDEDUCTIBLE]\n",
        ),
    ] = None
    income_account: Annotated[
        str | None,
        Field(
            alias="incomeAccount",
            description="Field is similar to vatType, it defaults to the product's income account. Either the line or the product needs to have an income account set.",
            examples=["3000"],
        ),
    ] = None
    net: Annotated[
        int | None,
        Field(
            description="Net amount (in creditNote currency) in cents.",
            examples=[25000],
        ),
    ] = None
    gross: Annotated[
        int | None,
        Field(
            description="Gross amount (= net+VAT) (in creditNote currency) in cents.",
            examples=[30000],
        ),
    ] = None
    project: ProjectResult | None = None


class DraftResult(BaseModel):
    draft_id: Annotated[
        int | None, Field(alias="draftId", description="Draft ID", examples=[2888156])
    ] = None
    uuid: Annotated[
        str | None,
        Field(
            description="UUID are represented as 32 hexadecimal (base-16) digits, displayed in 5 groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters.",
            examples=["123e4567-e89b-12d3-a456-426655440000"],
        ),
    ] = None
    invoice_issue_date: Annotated[
        date_aliased | None,
        Field(
            alias="invoiceIssueDate",
            description="Issue date of the draft, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    due_date: Annotated[
        date_aliased | None,
        Field(
            alias="dueDate",
            description="Due date of draft, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    invoice_number: Annotated[
        str | None,
        Field(
            alias="invoiceNumber",
            description="If invoice associated with draft, this is the invoice number (not to be confused with the invoiceId of an invoice issued from Fiken)",
            examples=["NOEE2888156"],
        ),
    ] = None
    contact: Contact | None = None
    project: ProjectResult | None = None
    cash: Annotated[
        bool | None,
        Field(description="If a cash sale/purchase (true) or otherwise (false)"),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code", examples=["NOK"], pattern="^[A-Z]{3}$"
        ),
    ] = None
    kid: Annotated[
        str | None,
        Field(
            description="Norwegian KID number. Number from 2 to 25 digits long.",
            examples=["5855454756"],
        ),
    ] = None
    paid: Annotated[
        bool | None,
        Field(
            description="Whether the sale/purchase has been paid (true) or not (false)"
        ),
    ] = None
    attachments: list[Attachment] | None = None
    payments: list[Payment] | None = None
    lines: list[DraftLineResult] | None = None


class InvoiceResult(BaseModel):
    invoice_id: Annotated[
        int | None,
        Field(alias="invoiceId", description="Invoice Id", examples=[2888156]),
    ] = None
    created_date: Annotated[
        date_aliased | None,
        Field(
            alias="createdDate",
            description="Date that the invoice was created in Fiken, format yyyy-mm-dd.",
            examples=["2023-04-03"],
        ),
    ] = None
    last_modified_date: Annotated[
        date_aliased | None,
        Field(
            alias="lastModifiedDate",
            description="Date that invoices was last modified in Fiken, format yyyy-mm-dd.",
            examples=["2018-04-03"],
        ),
    ] = None
    invoice_number: Annotated[
        int | None,
        Field(
            alias="invoiceNumber",
            description="Unique invoice number generated by us.",
            examples=[10001],
        ),
    ] = None
    kid: Annotated[
        str | None,
        Field(
            description="Norwegian KID number. Number from 2 to 25 digits long.",
            examples=["5855454756"],
        ),
    ] = None
    issue_date: Annotated[
        date_aliased | None,
        Field(
            alias="issueDate",
            description="Issue date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    due_date: Annotated[
        date_aliased | None,
        Field(
            alias="dueDate",
            description="Due date of the invoice, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    original_due_date: Annotated[
        date_aliased | None,
        Field(
            alias="originalDueDate",
            description="Original due date of the invoice if the due date has been changed, format yyyy-mm-dd",
            examples=["2018-04-03"],
        ),
    ] = None
    net: Annotated[
        int | None,
        Field(
            description="Net amount (in invoice currency) in cents.", examples=[25000]
        ),
    ] = None
    vat: Annotated[
        int | None,
        Field(
            description="VAT amount (in invoice currency) in cents.", examples=[5000]
        ),
    ] = None
    gross: Annotated[
        int | None,
        Field(
            description="Gross amount (= net+VAT) (in invoice currency) in cents.",
            examples=[30000],
        ),
    ] = None
    net_in_nok: Annotated[
        int | None,
        Field(
            alias="netInNok",
            description="Net amount in NOK (in cents)",
            examples=[25000],
        ),
    ] = None
    vat_in_nok: Annotated[
        int | None,
        Field(
            alias="vatInNok",
            description="VAT amount in NOK (in cents)",
            examples=[5000],
        ),
    ] = None
    gross_in_nok: Annotated[
        int | None,
        Field(
            alias="grossInNok",
            description="Gross amount in NOK (in cents)",
            examples=[30000],
        ),
    ] = None
    cash: Annotated[
        bool | None,
        Field(
            description="Purchase associated with Invoice is a cash purchase.",
            examples=[True],
        ),
    ] = None
    invoice_text: Annotated[
        str | None,
        Field(
            alias="invoiceText",
            description="Comment/description printed above the invoice lines",
        ),
    ] = None
    your_reference: Annotated[str | None, Field(alias="yourReference")] = None
    our_reference: Annotated[str | None, Field(alias="ourReference")] = None
    order_reference: Annotated[str | None, Field(alias="orderReference")] = None
    invoice_draft_uuid: Annotated[
        str | None,
        Field(
            alias="invoiceDraftUuid",
            description="The UUID of invoice draft used to create the invoice.",
            examples=["123e4567-e89b-12d3-a456-426655440000"],
        ),
    ] = None
    address: Address | None = None
    lines: list[InvoiceLineResult] | None = None
    currency: Annotated[
        str | None,
        Field(
            description="ISO 4217 currency code, default value is NOK",
            pattern="^[A-Z]{3}$",
        ),
    ] = "NOK"
    bank_account_number: Annotated[
        str | None, Field(alias="bankAccountNumber", examples=["11112233334"])
    ] = None
    sent_manually: Annotated[
        bool | None,
        Field(
            alias="sentManually",
            description='If the invoice was not sent using Fiken this can be set to "true"',
            examples=[False],
        ),
    ] = None
    invoice_pdf: Annotated[Attachment | None, Field(alias="invoicePdf")] = None
    associated_credit_notes: Annotated[
        list[int] | None,
        Field(
            alias="associatedCreditNotes", description="Associated credit note Id(s)"
        ),
    ] = None
    attachments: list[Attachment] | None = None
    customer: Contact | None = None
    sale: SaleResult | None = None
    project: ProjectResult | None = None
    dispatches: list[DispatchResult] | None = None
